public without sharing class InvoiceItemSelector {

//    private static InvoiceItemSelector instance = null;
//
//    public static InvoiceItemSelector getInstance() {
//        if (instance == null) {
//        instance = new InvoiceItemSelector();
//        }
//        return instance;
//    }
//
//    public List<InvoiceItem__c> selectByInvoiceId(Id invoiceId){
//        return [SELECT Id, Price__c, Type__c
//                FROM InvoiceItem__c
//                WHERE Invoice__c =: invoiceId ];
//    }

}